server:
  servlet:
    context-path: /cocoker
  port: 80
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    #    password: 5838a0dac35b6bc4
    password: zsrjlbz_520
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://119.188.210.188:3306/cocoker?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/cocoker?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
#    盐值
jasypt:
  encryptor:
    password: 26BA51F910C2F0E17658269214C51DF7

  #    url: jdbc:mysql://67.216.193.93:3306/huaibei?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true

wechat:
  #  mpAppId: wx4a8c4b0106bd18eb
  #  mpAppSecret: 72864f816dc4209b5bcc00e445f2573b
  #  mpAppId: wx680b8c9999a557d3
  #  mpAppSecret: 1411f8069ef85c13baa59725a5c60b04
  mpAppId: wxf464861a57967816
  mpAppSecret: 05f3011ce9057c29da74ede1cbd60c9d
  #  openAppId:
  #  openAppSecret:
  #  mchId: 1244448802
  #  mchKey: xxx
  #  keyPath: xxx
  #  notifyUrl:
  #  customeridY: 100954
  #  customerKey: j3S26ElTnPGpmgPPHEGufMMgr2fbJd6T
  #  notifyurlY: http://rhyme.nat300.top/cocoker/transaction/notifyurl
  #  returnurlY: http://rhyme.nat300.top/cocoker/transaction/returnurl
  #  payUrl: http://mc.hx988.cn/submitorder
  customeridY1: 20165
  customerKey1: 415290769594460E2E485922904F345D
  notifyurlY1: http://frqd.com.cn/cocoker/transaction/notifyurl
  returnurlY1: http://frqd.com.cn/cocoker/transaction/returnurl
  payUrl1: http://business.neubupay.com/api/api/pay
  customeridY2: 2019050111095458073843
  customerKey2: de775cbe3a2c4758b4cb8c435975b74e
  notifyurlY2: http://frqd.com.cn/cocoker/transaction/notifyurl2
  returnurlY2: http://frqd.com.cn/cocoker/transaction/returnurl2
  payUrl2: http://www.koulingfa.com/api/uni/pay

projecturl:
  oauth2buildAuthorizationUrl: http://frqd.com.cn
  #  returnUrl: http://lwvmzs.cn
  qrUrl: http://frqd.com.cn
  zeroMoney: http://jfcms12.com/jieru.php
  zeroMoneyUID: 2845
  zeroMoneyKey: a15005610038b
  moneylessthan5: 20
  moneylessthan25: 0
  moneylessthan50: 0
  moneylessthan100: 0
  moneylessthan500: 0
#logging:
#  level:
#    com.cocoker.service.impl: trace